services:
  java-template:
    image: java-template:dev
    container_name: java-template-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - /home/jia/workspace/java-template/logs:/app/logs
    ports:
      - "28080:8080"
