services:
  java-template:
    image: java-template:prod
    container_name: java-template-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/jia/workspace/java-template/logs:/app/logs
    ports:
      - "18080:8080"
