server:
  port: 8080
spring:
  application:
    name: "java-template"
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/template?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: "******"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  accessKeyId: "******"
  accessKeySecret: "******"
  ossUrl: "https://%s.oss-cn-hangzhou.aliyuncs.com/"
  ossEndpoint: "https://oss-cn-hangzhou.aliyuncs.com"
  ossRegion: "cn-hangzhou"
  ossBucket: "template"
