server:
  port: 8080
  domain: ""
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/template_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: "******"

aliyun:
  ossBucket: "template-dev"
